services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_matchmaking
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:15
    container_name: postgres_matchmaking
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: matchmaking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_matchmaking
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    

volumes:
  rabbitmq_data:
  postgres_data:
  redis_data: